use_frameworks!

platform :ios, '8.0'

target 'TestLibraryFromPodCmd_Example' do
  pod 'TestLibraryFromPodCmd', :path => '../'

  target 'TestLibraryFromPodCmd_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
